dist: trusty
sudo: require
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data

language: cpp
compiler:
  - gcc
  - clang

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: 
  - make
  - cd out/bin
  - ./unit_tests
